# -*- coding: utf-8 -*-
"""Prototype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M-AXhtEGAwMbHZ61BcOMmMV95Hurpy9o
"""

import streamlit as st
import pandas as pd
import joblib
from data_preprocessing import data_preprocessing, encoder_Course, encoder_Daytime_evening_attendance, encoder_Fathers_occupation, encoder_Fathers_qualification, encoder_Gender, encoder_Marital_status, encoder_Mothers_occupation, encoder_Mothers_qualification, encoder_Previous_qualification, encoder_Scholarship_holder
from prediction import prediction

col1, col2 = st.columns([1, 5])
with col1:
    st.image("https://github.com/Shue84/Jaya-Jaya/blob/main/JAYA%20JAYA.png", width=130)
with col2:
    st.header('Students Dropout Prediction (Prototype)')

# 1. Load the OneHotEncoder
onehot_encoder = joblib.load('onehot_encoder.joblib')  # Replace with your file path

# 2. Get Feature Names (Correct Method)
feature_names = onehot_encoder.get_feature_names_out(['Marital_status', 'Course', 'Previous_qualification'])
#This is the correct way to get the feature names.

# 3. Define Original Categorical Values
marital_status_options = ['Single', 'Married',  'Widower', 'Divorced', 'Facto Union', 'Legally separated']
course_options = ['33', '171', '8014', '9003', '9070', '9085', '9119', '9130', '9147', '9238', '9254', '9500', '9556', '9670', '9773' '9863', '9991']
qualification_options = ['1', '2', '3', '4', '5', '6', '9', '10', '12', '14', '15', '19', '38', '39', '40', '42', '43']

data = pd.DataFrame()

col1, col2, col3 = st.columns(3)

with col1:
    Age_at_enrollment = int(st.number_input(label='Age_at_enrollment', value=15))
    data["Age_at_enrollment"] = Age_at_enrollment

with col2:
    Gender = st.selectbox(label='Gender', options=encoder_Gender.classes_, index=1)
    data["Gender"] = [Gender]

with col3:
    Marital_status = st.selectbox('Marital Status', options=marital_status_options)
    data["Marital_status"] = Marital_status


col1, col2, col3 = st.columns(3)

with col1:
    Course = st.selectbox('Course', options=course_options)
    data["Course"] = Course

with col2:
    Daytime_evening_attendance = st.selectbox(label='Daytime_evening_attendance', options=encoder_Daytime_evening_attendance.classes_, index=1)
    data["Daytime_evening_attendance"] = Daytime_evening_attendance

with col3:
    Scholarship_holder = st.selectbox(label='Scholarship_holder', options=encoder_Scholarship_holder.classes_, index=1)
    data["Scholarship_holder"] = Scholarship_holder


col1, col2, col3, col4 = st.columns(4)

with col1:
    Fathers_qualification = st.selectbox(label='Fathers_qualification', options=encoder_Fathers_qualification.classes_, index=28)
    data["Fathers_qualification"] = Fathers_qualification

with col2:
    Mothers_qualification = st.selectbox(label='Mothers_qualification', options=encoder_Mothers_qualification.classes_, index=28)
    data["Mothers_qualification"] = Mothers_qualification

with col3:
    Fathers_occupation = st.selectbox(label='Fathers_occupation', options=encoder_Fathers_occupation.classes_, index=31)
    data["Fathers_occupation"] = Fathers_occupation

with col4:
    Mothers_occupation = st.selectbox(label='Mothers_occupation', options=encoder_Mothers_occupation.classes_, index=31)
    data["Mothers_occupation"] = Mothers_occupation

col1, col2 = st.columns(2)

with col1:
    Previous_qualification = st.selectbox('Previous Qualification', options=qualification_options)
    data["Previous_qualification"] = Previous_qualification

with col2:
    Previous_qualification_grade = int(st.number_input(label='Previous_qualification_grade', value=0))
    data["Previous_qualification_grade"] = Previous_qualification_grade


col1, col2 = st.columns(2)

with col1:
    Curriculum_units_1st_sem_approved = int(st.number_input(label='Curriculum_units_1st_sem_approved', value=0))
    data["Curriculum_units_1st_sem_approved"] = Curriculum_units_1st_sem_approved

with col2:
    Curriculum_units_2nd_sem_approved = int(st.number_input(label='Curriculum_units_2nd_sem_approved', value=0))
    data["Curriculum_units_2nd_sem_approved"] = Curriculum_units_2nd_sem_approved


col1, col2 = st.columns(2)

with col1:
    Curriculum_units_1st_sem_grade = int(st.number_input(label='Curriculum_units_1st_sem_grade', value=0))
    data["Curriculum_units_1st_sem_grade"] = Curriculum_units_1st_sem_grade

with col2:
    Curriculum_units_2nd_sem_grade = int(st.number_input(label='Curriculum_units_2nd_sem_grade', value=0))
    data["Curriculum_units_2nd_sem_grade"] = Curriculum_units_2nd_sem_grade

with st.expander("View the Raw Data"):
    st.dataframe(data=data, width=800, height=10)

if st.button('Predict'):
    new_data = data_preprocessing(data=data)
    with st.expander("View the Preprocessed Data"):
        st.dataframe(data=new_data, width=800, height=10)
    st.write("Status: {}".format(prediction(new_data)))